# Generated by Django 2.2.6 on 2019-10-26 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0008_tweet_liked'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tweet',
            old_name='Liked',
            new_name='liked',
        ),
    ]
