# Generated by Django 2.2.6 on 2019-10-26 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0009_auto_20191026_1116'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tweet',
            old_name='liked',
            new_name='Liked',
        ),
    ]
